// Mocks generated by Mockito 5.4.6 from annotations
// in sinapsis/test/features/notes/presentation/bloc/notes_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sinapsis/core/errors/failures.dart' as _i6;
import 'package:sinapsis/features/notes/domain/entities/note.dart' as _i7;
import 'package:sinapsis/features/notes/domain/repositories/notes_repository.dart'
    as _i2;
import 'package:sinapsis/features/notes/domain/usecases/create_note.dart'
    as _i8;
import 'package:sinapsis/features/notes/domain/usecases/delete_note.dart'
    as _i10;
import 'package:sinapsis/features/notes/domain/usecases/get_notes_by_course.dart'
    as _i4;
import 'package:sinapsis/features/notes/domain/usecases/update_note.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeNotesRepository_0 extends _i1.SmartFake
    implements _i2.NotesRepository {
  _FakeNotesRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetNotesByCourse].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetNotesByCourse extends _i1.Mock implements _i4.GetNotesByCourse {
  MockGetNotesByCourse() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NotesRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeNotesRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.NotesRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Note>>> call(
    String? userId,
    String? courseId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            userId,
            courseId,
          ],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, List<_i7.Note>>>.value(
            _FakeEither_1<_i6.Failure, List<_i7.Note>>(
          this,
          Invocation.method(
            #call,
            [
              userId,
              courseId,
            ],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Note>>>);
}

/// A class which mocks [CreateNote].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateNote extends _i1.Mock implements _i8.CreateNote {
  MockCreateNote() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NotesRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeNotesRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.NotesRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Note>> call({
    required String? courseId,
    required String? userId,
    required String? title,
    required String? content,
    List<String>? tags,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #courseId: courseId,
            #userId: userId,
            #title: title,
            #content: content,
            #tags: tags,
          },
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Note>>.value(
            _FakeEither_1<_i6.Failure, _i7.Note>(
          this,
          Invocation.method(
            #call,
            [],
            {
              #courseId: courseId,
              #userId: userId,
              #title: title,
              #content: content,
              #tags: tags,
            },
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.Note>>);
}

/// A class which mocks [UpdateNote].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateNote extends _i1.Mock implements _i9.UpdateNote {
  MockUpdateNote() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NotesRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeNotesRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.NotesRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Note>> call(_i7.Note? note) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [note],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Note>>.value(
            _FakeEither_1<_i6.Failure, _i7.Note>(
          this,
          Invocation.method(
            #call,
            [note],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.Note>>);
}

/// A class which mocks [DeleteNote].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteNote extends _i1.Mock implements _i10.DeleteNote {
  MockDeleteNote() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NotesRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeNotesRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.NotesRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [id],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}
