// Mocks generated by Mockito 5.4.6 from annotations
// in sinapsis/test/features/notes/domain/usecases/notes_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sinapsis/core/errors/failures.dart' as _i5;
import 'package:sinapsis/features/notes/domain/entities/note.dart' as _i6;
import 'package:sinapsis/features/notes/domain/repositories/notes_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NotesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotesRepository extends _i1.Mock implements _i3.NotesRepository {
  MockNotesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Note>>> getAllNotes(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllNotes,
          [userId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i6.Note>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.Note>>(
          this,
          Invocation.method(
            #getAllNotes,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Note>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Note>>> getNotesByCourse(
    String? userId,
    String? courseId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotesByCourse,
          [
            userId,
            courseId,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i6.Note>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.Note>>(
          this,
          Invocation.method(
            #getNotesByCourse,
            [
              userId,
              courseId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Note>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Note>> getNote(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNote,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Note>>.value(
            _FakeEither_0<_i5.Failure, _i6.Note>(
          this,
          Invocation.method(
            #getNote,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Note>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Note>> createNote({
    required String? courseId,
    required String? userId,
    required String? title,
    required String? content,
    List<String>? tags,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createNote,
          [],
          {
            #courseId: courseId,
            #userId: userId,
            #title: title,
            #content: content,
            #tags: tags,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Note>>.value(
            _FakeEither_0<_i5.Failure, _i6.Note>(
          this,
          Invocation.method(
            #createNote,
            [],
            {
              #courseId: courseId,
              #userId: userId,
              #title: title,
              #content: content,
              #tags: tags,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Note>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Note>> updateNote(_i6.Note? note) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateNote,
          [note],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Note>>.value(
            _FakeEither_0<_i5.Failure, _i6.Note>(
          this,
          Invocation.method(
            #updateNote,
            [note],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Note>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteNote(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteNote,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteNote,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Note>>> searchNotes(
    String? userId,
    String? query,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchNotes,
          [
            userId,
            query,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i6.Note>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.Note>>(
          this,
          Invocation.method(
            #searchNotes,
            [
              userId,
              query,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Note>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Note>>> getNotesByTags(
    String? userId,
    List<String>? tags,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotesByTags,
          [
            userId,
            tags,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i6.Note>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.Note>>(
          this,
          Invocation.method(
            #getNotesByTags,
            [
              userId,
              tags,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Note>>>);
}
