targets:
  $default:
    builders:
      freezed:
        enabled: true
      json_serializable:
        enabled: true
      drift_dev:
        enabled: true
        options:
          sql:
            dialect: sqlite
            options:
              modules: []
          store_date_time_values_as_text: true
