// Mocks generated by Mockito 5.4.6 from annotations
// in sinapsis/test/features/notes/data/repositories/notes_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:sinapsis/features/notes/data/datasources/notes_local_datasource.dart'
    as _i2;
import 'package:sinapsis/features/notes/data/models/note_model.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [NotesLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotesLocalDataSource extends _i1.Mock
    implements _i2.NotesLocalDataSource {
  MockNotesLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.NoteModel>> getAllNotes(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllNotes,
          [userId],
        ),
        returnValue: _i3.Future<List<_i4.NoteModel>>.value(<_i4.NoteModel>[]),
      ) as _i3.Future<List<_i4.NoteModel>>);

  @override
  _i3.Future<List<_i4.NoteModel>> getNotesByCourse(
    String? userId,
    String? courseId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotesByCourse,
          [
            userId,
            courseId,
          ],
        ),
        returnValue: _i3.Future<List<_i4.NoteModel>>.value(<_i4.NoteModel>[]),
      ) as _i3.Future<List<_i4.NoteModel>>);

  @override
  _i3.Future<_i4.NoteModel> getNote(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getNote,
          [id],
        ),
        returnValue:
            _i3.Future<_i4.NoteModel>.value(_i5.dummyValue<_i4.NoteModel>(
          this,
          Invocation.method(
            #getNote,
            [id],
          ),
        )),
      ) as _i3.Future<_i4.NoteModel>);

  @override
  _i3.Future<void> saveNote(_i4.NoteModel? note) => (super.noSuchMethod(
        Invocation.method(
          #saveNote,
          [note],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateNote(_i4.NoteModel? note) => (super.noSuchMethod(
        Invocation.method(
          #updateNote,
          [note],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteNote(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteNote,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.NoteModel>> searchNotes(
    String? userId,
    String? query,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchNotes,
          [
            userId,
            query,
          ],
        ),
        returnValue: _i3.Future<List<_i4.NoteModel>>.value(<_i4.NoteModel>[]),
      ) as _i3.Future<List<_i4.NoteModel>>);

  @override
  _i3.Future<List<_i4.NoteModel>> getNotesByTags(
    String? userId,
    List<String>? tags,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotesByTags,
          [
            userId,
            tags,
          ],
        ),
        returnValue: _i3.Future<List<_i4.NoteModel>>.value(<_i4.NoteModel>[]),
      ) as _i3.Future<List<_i4.NoteModel>>);
}
