name: Build Windows Release

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'
          channel: 'stable'

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Create .env file
        run: |
          echo "SUPABASE_URL=https://placeholder.supabase.co" > .env
          echo "SUPABASE_ANON_KEY=placeholder-anon-key" >> .env
          echo "SENTRY_DSN=https://placeholder-sentry-dsn" >> .env
          echo "APP_ENV=demo" >> .env

      - name: Get Dependencies
        run: flutter pub get

      - name: Generate Code
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build Windows Release
        run: flutter build windows --release

      - name: Create ZIP Archive
        run: |
          cd build/windows/x64/runner/Release
          Compress-Archive -Path * -DestinationPath ../../../../../sinapsis-windows.zip

      - name: Upload Windows Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sinapsis-windows-release
          path: sinapsis-windows.zip
          retention-days: 30

      - name: Create Release (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: sinapsis-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
